# Generated by Django 5.1.4 on 2026-07-02 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classroom", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="homework/",
                        verbose_name="附件",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="截止时间"
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=1, default=100, max_digits=6, verbose_name="分值"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("closed", "已截止"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homeworks",
                        to="classroom.classroom",
                        verbose_name="班级",
                    ),
                ),
            ],
            options={
                "verbose_name": "作业",
                "verbose_name_plural": "作业",
            },
        ),
        migrations.CreateModel(
            name="HomeworkSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("content", models.TextField(blank=True, verbose_name="提交内容")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="homework_submit/",
                        verbose_name="附件",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "is_late",
                    models.BooleanField(default=False, verbose_name="逾期提交"),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="得分",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="评语")),
                (
                    "correct_status",
                    models.CharField(
                        choices=[
                            ("submitted", "已提交"),
                            ("graded", "已批改"),
                            ("returned", "已发布成绩"),
                        ],
                        default="submitted",
                        max_length=16,
                        verbose_name="批改状态",
                    ),
                ),
                (
                    "auto_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="AI 建议分",
                    ),
                ),
                (
                    "auto_comment",
                    models.TextField(blank=True, verbose_name="AI 建议评语"),
                ),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="homework.homework",
                        verbose_name="作业",
                    ),
                ),
            ],
            options={
                "verbose_name": "作业提交",
                "verbose_name_plural": "作业提交",
            },
        ),
    ]
