# Generated by Django 5.1.4 on 2026-07-15 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0003_homework_course"),
        ("questions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="mode",
            field=models.CharField(
                choices=[
                    ("attachment", "附件/文本作业"),
                    ("questions", "题库选题作业"),
                ],
                default="attachment",
                max_length=16,
                verbose_name="作业模式",
            ),
        ),
        migrations.AddField(
            model_name="homeworksubmission",
            name="objective_score",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=6, verbose_name="客观题得分"
            ),
        ),
        migrations.CreateModel(
            name="HomeworkQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=1,
                        default=5,
                        max_digits=5,
                        verbose_name="题目分值",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="题目顺序"),
                ),
                (
                    "snapshot",
                    models.JSONField(blank=True, default=dict, verbose_name="题目快照"),
                ),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="homework.homework",
                        verbose_name="作业",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homework_items",
                        to="questions.question",
                        verbose_name="来源题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "作业题目",
                "verbose_name_plural": "作业题目",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomeworkAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "student_answer",
                    models.JSONField(blank=True, default=dict, verbose_name="学生答案"),
                ),
                (
                    "is_correct",
                    models.BooleanField(blank=True, null=True, verbose_name="是否正确"),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="得分",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="批改评语")),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="批改时间"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_items",
                        to="homework.homeworksubmission",
                        verbose_name="作业提交",
                    ),
                ),
                (
                    "homework_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="homework.homeworkquestion",
                        verbose_name="作业题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "作业答题记录",
                "verbose_name_plural": "作业答题记录",
                "ordering": ["homework_question__order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="homeworkquestion",
            constraint=models.UniqueConstraint(
                fields=("homework", "question"), name="unique_homework_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="homeworkquestion",
            constraint=models.UniqueConstraint(
                fields=("homework", "order"), name="unique_homework_question_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="homeworkanswer",
            constraint=models.UniqueConstraint(
                fields=("submission", "homework_question"),
                name="unique_submission_homework_question",
            ),
        ),
    ]
