# Generated by Codex on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0004_homework_mode_homeworksubmission_objective_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
        ),
    ]
