# Generated by Django 5.1.4 on 2026-08-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0005_homework_start_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homework",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "作业",
                "verbose_name_plural": "作业",
            },
        ),
        migrations.AlterModelOptions(
            name="homeworksubmission",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "作业提交",
                "verbose_name_plural": "作业提交",
            },
        ),
    ]
