# Generated by Django 5.1.4 on 2026-09-02 07:44

import apps.homework.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0006_alter_homework_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.homework.models._homework_file_path,
                verbose_name="附件",
            ),
        ),
        migrations.AlterField(
            model_name="homeworksubmission",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.homework.models._submission_file_path,
                verbose_name="附件",
            ),
        ),
    ]
