# Generated by Django 5.1.4 on 2026-08-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=False, verbose_name="首次登录需修改密码"),
        ),
    ]
