# Generated by Django 5.1.4 on 2026-09-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='ntype',
            field=models.CharField(choices=[('homework', '作业'), ('exam', '考试'), ('lab', '实验'), ('system', '系统')], default='system', max_length=16, verbose_name='类型'),
        ),
    ]
