# Generated by Django 5.1.4 on 2026-07-21 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("mock", "模拟模式"),
                            ("deepseek", "DeepSeek"),
                            ("tongyi", "通义千问"),
                            ("zhipu", "智谱 GLM"),
                            ("openai", "OpenAI 兼容接口"),
                        ],
                        default="mock",
                        max_length=20,
                        verbose_name="服务商",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=False, verbose_name="启用配置"),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="接口地址"
                    ),
                ),
                (
                    "chat_model",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="对话模型"
                    ),
                ),
                (
                    "embed_model",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="向量模型"
                    ),
                ),
                (
                    "tts_model",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="语音模型"
                    ),
                ),
                (
                    "api_key_ciphertext",
                    models.TextField(blank=True, verbose_name="加密 API Key"),
                ),
                (
                    "last_test_status",
                    models.CharField(
                        choices=[
                            ("untested", "未测试"),
                            ("success", "连接成功"),
                            ("failed", "连接失败"),
                        ],
                        default="untested",
                        max_length=16,
                        verbose_name="测试状态",
                    ),
                ),
                (
                    "last_test_message",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="测试结果"
                    ),
                ),
                (
                    "last_tested_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="测试时间"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_configuration_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="最后修改人",
                    ),
                ),
            ],
            options={
                "verbose_name": "大模型配置",
                "verbose_name_plural": "大模型配置",
            },
        ),
    ]
