# Generated by Django 5.1.4 on 2026-07-02 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classroom", "0002_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="文件名称"),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="文件类型"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="materials/",
                        verbose_name="文件",
                    ),
                ),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("pending", "待解析"),
                            ("parsing", "解析中"),
                            ("done", "已入库"),
                            ("failed", "解析失败"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="解析状态",
                    ),
                ),
                (
                    "qa_open",
                    models.BooleanField(default=True, verbose_name="对学生开放提问"),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="classroom.classroom",
                        verbose_name="班级",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "教辅资料",
                "verbose_name_plural": "教辅资料",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("content", models.TextField(verbose_name="片段内容")),
                (
                    "page",
                    models.IntegerField(blank=True, null=True, verbose_name="页码"),
                ),
                (
                    "embedding",
                    models.JSONField(blank=True, default=list, verbose_name="向量"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge.material",
                        verbose_name="来源资料",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库片段",
                "verbose_name_plural": "知识库片段",
            },
        ),
        migrations.CreateModel(
            name="QARecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("question", models.TextField(verbose_name="问题")),
                ("answer", models.TextField(blank=True, verbose_name="回答")),
                (
                    "cited_chunks",
                    models.JSONField(blank=True, default=list, verbose_name="引用片段"),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="classroom.classroom",
                        verbose_name="班级",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_records",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库问答记录",
                "verbose_name_plural": "知识库问答记录",
            },
        ),
    ]
