# Generated by Django 5.1.4 on 2026-07-18 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        ("knowledge", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qarecord",
            name="catalog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.catalog",
                verbose_name="章节",
            ),
        ),
    ]
