# Generated by Django 5.1.4 on 2026-07-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_qarecord_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="qarecord",
            name="session",
            field=models.CharField(
                db_index=True, default="", max_length=64, verbose_name="会话标识"
            ),
        ),
    ]
