# Generated by Django 5.1.4 on 2026-08-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0004_qarecord_session"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qarecord",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "知识库问答记录",
                "verbose_name_plural": "知识库问答记录",
            },
        ),
    ]
