# Generated by Django 5.1.4 on 2026-09-02 07:44

import apps.knowledge.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0005_alter_qarecord_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.knowledge.models._material_file_path,
                verbose_name="文件",
            ),
        ),
    ]
