# Generated by Django 5.1.4 on 2026-07-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnswerRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "scene",
                    models.CharField(
                        choices=[
                            ("practice", "章节练习"),
                            ("homework", "作业"),
                            ("exam", "考试"),
                        ],
                        default="practice",
                        max_length=16,
                        verbose_name="场景类型",
                    ),
                ),
                (
                    "scene_ref_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="场景对象编号"
                    ),
                ),
                (
                    "student_answer",
                    models.JSONField(blank=True, default=dict, verbose_name="学生答案"),
                ),
                (
                    "is_correct",
                    models.BooleanField(blank=True, null=True, verbose_name="是否正确"),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="得分",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
            ],
            options={
                "verbose_name": "答题记录",
                "verbose_name_plural": "答题记录",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "qtype",
                    models.CharField(
                        choices=[
                            ("single", "单选题"),
                            ("multi", "多选题"),
                            ("judge", "判断题"),
                            ("blank", "填空题"),
                            ("short", "简答题"),
                        ],
                        max_length=16,
                        verbose_name="题型",
                    ),
                ),
                ("stem", models.TextField(verbose_name="题干")),
                (
                    "options",
                    models.JSONField(blank=True, default=list, verbose_name="选项"),
                ),
                (
                    "answer",
                    models.JSONField(blank=True, default=dict, verbose_name="答案"),
                ),
                ("analysis", models.TextField(blank=True, verbose_name="解析")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=1, default=5, max_digits=5, verbose_name="分值"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "简单"),
                            ("medium", "中等"),
                            ("hard", "困难"),
                        ],
                        default="medium",
                        max_length=16,
                        verbose_name="难度",
                    ),
                ),
                (
                    "knowledge_tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="知识点标签"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("ai", "AI 生成"), ("manual", "手动添加")],
                        default="manual",
                        max_length=16,
                        verbose_name="来源",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("published", "已发布"),
                            ("disabled", "停用"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目",
                "verbose_name_plural": "题目",
            },
        ),
    ]
