# Generated by Django 5.1.4 on 2026-08-05 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_videowatchprogress_page_count_and_more"),
        ("questions", "0003_strict_question_catalog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WrongNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("stem", models.TextField(verbose_name="题干")),
                (
                    "my_answer",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="我的答案"
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="正确答案"
                    ),
                ),
                ("analysis", models.TextField(blank=True, verbose_name="解析/笔记")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrong_notes",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrong_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "手动错题",
                "verbose_name_plural": "手动错题",
                "ordering": ["-id"],
            },
        ),
    ]
