# Generated by Django 5.1.4 on 2026-08-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_wrongmastery"),
    ]

    operations = [
        migrations.AddField(
            model_name="wrongmastery",
            name="removed",
            field=models.BooleanField(default=False, verbose_name="已从错题本移除"),
        ),
    ]
