# Generated by Django 5.1.4 on 2026-07-02 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classroom", "0002_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "answers",
                    models.JSONField(blank=True, default=dict, verbose_name="作答内容"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "objective_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="客观题得分",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="总分",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "未开始"),
                            ("in_progress", "考试中"),
                            ("submitted", "已提交"),
                            ("timeout", "超时交卷"),
                            ("absent", "缺考"),
                        ],
                        default="not_started",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "abnormal",
                    models.BooleanField(default=False, verbose_name="异常标记"),
                ),
            ],
            options={
                "verbose_name": "考试答卷",
                "verbose_name_plural": "考试答卷",
            },
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("random", "随机组卷"), ("manual", "手动组卷")],
                        default="random",
                        max_length=16,
                        verbose_name="组卷方式",
                    ),
                ),
                (
                    "question_items",
                    models.JSONField(blank=True, default=list, verbose_name="题目列表"),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=1, default=0, max_digits=6, verbose_name="总分"
                    ),
                ),
            ],
            options={
                "verbose_name": "试卷",
                "verbose_name_plural": "试卷",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="考试名称")),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(default=60, verbose_name="考试时长(分钟)"),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=1, default=100, max_digits=6, verbose_name="总分"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("finished", "已结束"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(default=False, verbose_name="题目乱序"),
                ),
                (
                    "shuffle_options",
                    models.BooleanField(default=False, verbose_name="选项乱序"),
                ),
                (
                    "show_analysis_after",
                    models.BooleanField(default=True, verbose_name="结束后展示解析"),
                ),
                (
                    "allow_resubmit",
                    models.BooleanField(
                        default=False, verbose_name="允许重复提交(取最后一次)"
                    ),
                ),
                (
                    "per_student_paper",
                    models.BooleanField(default=False, verbose_name="每人不同试卷"),
                ),
                (
                    "anti_cheat",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="防作弊配置"
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="classroom.classroom",
                        verbose_name="班级",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "考试",
                "verbose_name_plural": "考试",
            },
        ),
        migrations.CreateModel(
            name="ExamLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("action", models.CharField(max_length=50, verbose_name="操作类型")),
                (
                    "happened_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                ("ip", models.CharField(blank=True, max_length=64, verbose_name="IP")),
                (
                    "device",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="设备信息"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="备注"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="exams.exam",
                        verbose_name="考试",
                    ),
                ),
            ],
            options={
                "verbose_name": "考试操作日志",
                "verbose_name_plural": "考试操作日志",
            },
        ),
    ]
