# Generated by Django 5.1.4 on 2026-07-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsubmission",
            name="score_released",
            field=models.BooleanField(default=False, verbose_name="成绩已发布"),
        ),
        migrations.AddField(
            model_name="examsubmission",
            name="subjective_scores",
            field=models.JSONField(blank=True, default=dict, verbose_name="主观题得分"),
        ),
    ]
