# Generated by Django 5.1.4 on 2026-08-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_examsubmission_score_released_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exam",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "考试",
                "verbose_name_plural": "考试",
            },
        ),
        migrations.AlterModelOptions(
            name="examlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "考试操作日志",
                "verbose_name_plural": "考试操作日志",
            },
        ),
        migrations.AlterModelOptions(
            name="examsubmission",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "考试答卷",
                "verbose_name_plural": "考试答卷",
            },
        ),
    ]
