# Generated by Django 5.1.4 on 2026-07-02 07:17

import apps.classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="班级名称")),
                (
                    "invite_code",
                    models.CharField(
                        default=apps.classroom.models.gen_invite_code,
                        max_length=16,
                        unique=True,
                        verbose_name="邀请码",
                    ),
                ),
                (
                    "invite_enabled",
                    models.BooleanField(default=True, verbose_name="邀请码开启"),
                ),
                (
                    "start_at",
                    models.DateField(blank=True, null=True, verbose_name="开课时间"),
                ),
                (
                    "end_at",
                    models.DateField(blank=True, null=True, verbose_name="结课时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "开课中"), ("closed", "已结课")],
                        default="open",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "班级",
                "verbose_name_plural": "班级",
            },
        ),
        migrations.CreateModel(
            name="ClassStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "learn_status",
                    models.CharField(
                        choices=[
                            ("active", "学习中"),
                            ("inactive", "未活跃"),
                            ("removed", "已移除"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="学习状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "班级学生",
                "verbose_name_plural": "班级学生",
            },
        ),
    ]
