# Generated by Django 5.1.4 on 2026-07-02 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classroom", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="教师",
            ),
        ),
        migrations.AddField(
            model_name="classstudent",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="classroom.classroom",
                verbose_name="班级",
            ),
        ),
        migrations.AddField(
            model_name="classstudent",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="joined_classes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="学生",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classstudent",
            unique_together={("classroom", "student")},
        ),
    ]
