# Generated by Django 5.1.4 on 2026-07-02 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="课程名称")),
                ("intro", models.TextField(blank=True, verbose_name="课程简介")),
                (
                    "cover",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="课程封面"
                    ),
                ),
                (
                    "term",
                    models.CharField(blank=True, max_length=50, verbose_name="学期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "启用"),
                            ("inactive", "停用"),
                            ("archived", "归档"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
            },
        ),
        migrations.CreateModel(
            name="PPTResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="文件名称"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="ppt/", verbose_name="文件"
                    ),
                ),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("pending", "待解析"),
                            ("parsing", "解析中"),
                            ("done", "已解析"),
                            ("failed", "解析失败"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="解析状态",
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="版本号")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="当前启用版本"),
                ),
                (
                    "parsed_pages",
                    models.JSONField(
                        blank=True, default=list, verbose_name="解析页数据"
                    ),
                ),
            ],
            options={
                "verbose_name": "PPT 资源",
                "verbose_name_plural": "PPT 资源",
            },
        ),
        migrations.CreateModel(
            name="TeachingVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "scripts",
                    models.JSONField(
                        blank=True, default=list, verbose_name="逐页讲解稿"
                    ),
                ),
                (
                    "audio_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="AI 配音地址"
                    ),
                ),
                (
                    "subtitle_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="字幕地址"
                    ),
                ),
                (
                    "video_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="视频地址"
                    ),
                ),
                (
                    "gen_status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("script_ready", "讲解稿就绪"),
                            ("audio_ready", "配音就绪"),
                            ("composing", "合成中"),
                            ("done", "已合成"),
                            ("failed", "生成失败"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="生成状态",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="是否发布"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "教学视频",
                "verbose_name_plural": "教学视频",
            },
        ),
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="章节标题")),
                ("order", models.IntegerField(default=0, verbose_name="排序号")),
                ("intro", models.TextField(blank=True, verbose_name="简介")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="是否发布"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="courses.catalog",
                        verbose_name="父级目录",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程目录",
                "verbose_name_plural": "课程目录",
                "ordering": ["order", "id"],
            },
        ),
    ]
