# Generated by Django 5.1.4 on 2026-07-02 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="授课教师",
            ),
        ),
        migrations.AddField(
            model_name="catalog",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalogs",
                to="courses.course",
                verbose_name="课程",
            ),
        ),
        migrations.AddField(
            model_name="pptresource",
            name="catalog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ppts",
                to="courses.catalog",
                verbose_name="章节",
            ),
        ),
        migrations.AddField(
            model_name="pptresource",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ppts",
                to="courses.course",
                verbose_name="课程",
            ),
        ),
        migrations.AddField(
            model_name="teachingvideo",
            name="catalog",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to="courses.catalog",
                verbose_name="章节",
            ),
        ),
        migrations.AddField(
            model_name="teachingvideo",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="courses.course",
                verbose_name="课程",
            ),
        ),
        migrations.AddField(
            model_name="teachingvideo",
            name="ppt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="videos",
                to="courses.pptresource",
                verbose_name="来源 PPT",
            ),
        ),
    ]
