# Generated by Django 5.1.4 on 2026-07-28 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoWatchProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("last_page", models.IntegerField(default=0, verbose_name="当前页索引")),
                (
                    "last_position",
                    models.FloatField(default=0, verbose_name="页内播放位置(秒)"),
                ),
                (
                    "watch_seconds",
                    models.IntegerField(default=0, verbose_name="累计学习时长(秒)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "未开始"),
                            ("in_progress", "学习中"),
                            ("completed", "已完成"),
                        ],
                        default="in_progress",
                        max_length=16,
                        verbose_name="学习状态",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_progress",
                        to="courses.teachingvideo",
                        verbose_name="教学视频",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频学习进度",
                "verbose_name_plural": "视频学习进度",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "video"),
                        name="unique_student_video_progress",
                    )
                ],
            },
        ),
    ]
