# Generated by Django 5.1.4 on 2026-08-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_videowatchprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="videowatchprogress",
            name="total_seconds",
            field=models.FloatField(default=0, verbose_name="音视频总时长(秒)"),
        ),
    ]
