# Generated by Django 5.1.4 on 2026-08-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_videowatchprogress_total_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="videowatchprogress",
            name="page_count",
            field=models.IntegerField(default=0, verbose_name="章节总页数"),
        ),
        migrations.AddField(
            model_name="videowatchprogress",
            name="page_durations",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="每页音视频时长(秒)"
            ),
        ),
        migrations.AddField(
            model_name="videowatchprogress",
            name="page_watched",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="每页已看时长(秒)"
            ),
        ),
    ]
