# Generated by Django 5.1.4 on 2026-09-02 07:44

import apps.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_videowatchprogress_page_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pptresource",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.courses.models._ppt_file_path,
                verbose_name="文件",
            ),
        ),
    ]
