# Generated by Django 5.1.4 on 2026-09-19 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_pptresource_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('kind', models.CharField(choices=[('mindmap', '思维导图'), ('demo', '交互演示')], max_length=16, verbose_name='资源类型')),
                ('title', models.CharField(max_length=200, verbose_name='资源标题')),
                ('path', models.CharField(max_length=255, verbose_name='资源路径')),
                ('intro', models.TextField(blank=True, verbose_name='资源说明')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序号')),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='courses.catalog', verbose_name='章节')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程资源',
                'verbose_name_plural': '课程资源',
                'ordering': ['course_id', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('course', 'path'), name='unique_course_resource_path')],
            },
        ),
    ]
