# Generated by Django 5.1.4 on 2026-09-19 02:35

import apps.courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_courseresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='视频标题')),
                ('file', models.FileField(upload_to=apps.courses.models._course_video_file_path, verbose_name='视频文件')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='时长(秒)')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序号')),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_videos', to='courses.catalog', verbose_name='章节')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_videos', to='courses.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '数字人视频',
                'verbose_name_plural': '数字人视频',
                'ordering': ['course_id', 'order', 'id'],
            },
        ),
    ]
