# Generated by Django 5.1.4 on 2026-09-19 01:48

import apps.labs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0004_classroom_courses'),
        ('courses', '0006_alter_pptresource_file'),
        ('questions', '0006_wrongmastery_removed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='模板编码')),
                ('title', models.CharField(max_length=128, verbose_name='实验名称')),
                ('description', models.TextField(blank=True, verbose_name='实验说明')),
                ('static_path', models.CharField(blank=True, max_length=255, verbose_name='静态页路径')),
                ('default_standard_minutes', models.PositiveIntegerField(default=30, verbose_name='标准时长(分钟)')),
                ('random_config', models.JSONField(blank=True, default=dict, verbose_name='随机参数配置')),
                ('cover', models.CharField(blank=True, max_length=500, verbose_name='封面/图标')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序号')),
            ],
            options={
                'verbose_name': '实验模板',
                'verbose_name_plural': '实验模板',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=128, verbose_name='实验名称')),
                ('description', models.TextField(blank=True, verbose_name='实验说明')),
                ('standard_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='标准时长(分钟)')),
                ('total_score', models.DecimalField(decimal_places=1, default=100, max_digits=6, verbose_name='总分')),
                ('pass_score', models.DecimalField(decimal_places=1, default=60, max_digits=6, verbose_name='及格分')),
                ('question_weight', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='题目权重')),
                ('random_config', models.JSONField(blank=True, default=dict, verbose_name='随机参数配置')),
                ('time_limit_seconds', models.IntegerField(blank=True, null=True, verbose_name='限时(秒)')),
                ('allow_resubmit', models.BooleanField(default=False, verbose_name='允许学生重复提交')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('closed', '已下线')], default='draft', max_length=16, verbose_name='状态')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序号')),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs', to='courses.catalog', verbose_name='章节')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='courses.course', verbose_name='课程')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labs', to='labs.labtemplate', verbose_name='实验模板')),
            ],
            options={
                'verbose_name': '实验',
                'verbose_name_plural': '实验',
                'ordering': ['course_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LabQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('score', models.DecimalField(decimal_places=1, default=5, max_digits=5, verbose_name='题目分值')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='题目顺序')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='题目快照')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='labs.lab', verbose_name='实验')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_items', to='questions.question', verbose_name='来源题目')),
            ],
            options={
                'verbose_name': '实验题目',
                'verbose_name_plural': '实验题目',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LabSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('open_at', models.DateTimeField(blank=True, null=True, verbose_name='开放时间')),
                ('close_at', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_schedules', to='classroom.classroom', verbose_name='班级')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='labs.lab', verbose_name='实验')),
            ],
            options={
                'verbose_name': '实验排课',
                'verbose_name_plural': '实验排课',
                'ordering': ['open_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LabSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('submitted', '已提交')], default='in_progress', max_length=16, verbose_name='状态')),
                ('attempt', models.PositiveIntegerField(default=1, verbose_name='第几次作答')),
                ('random_seed', models.JSONField(blank=True, default=dict, verbose_name='随机参数')),
                ('error_log', models.JSONField(blank=True, default=list, verbose_name='错误日志')),
                ('steps_result', models.JSONField(blank=True, default=dict, verbose_name='步骤结果')),
                ('elapsed_seconds', models.IntegerField(default=0, verbose_name='用时(秒)')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='错误次数')),
                ('passed_steps', models.PositiveIntegerField(default=0, verbose_name='通过步骤数')),
                ('total_steps', models.PositiveIntegerField(default=0, verbose_name='总步骤数')),
                ('base_score', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='基础分')),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='操作准确性')),
                ('efficiency_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='完成效率')),
                ('completion_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='完成度')),
                ('question_score', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='题目得分')),
                ('total_score', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='总分')),
                ('score_breakdown', models.JSONField(blank=True, default=dict, verbose_name='评分明细')),
                ('subjective_scores', models.JSONField(blank=True, default=dict, verbose_name='主观题得分')),
                ('reviewed', models.BooleanField(default=False, verbose_name='教师已复核')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('abnormal', models.BooleanField(default=False, verbose_name='异常标记')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('reset_at', models.DateTimeField(blank=True, null=True, verbose_name='重置时间')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='labs.lab', verbose_name='实验')),
                ('reset_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_resets', to=settings.AUTH_USER_MODEL, verbose_name='重置人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_reviews', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='labs.labschedule', verbose_name='排课')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_submissions', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '实验作答',
                'verbose_name_plural': '实验作答',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('conclusion', models.TextField(blank=True, verbose_name='实验结论')),
                ('file_docx', models.FileField(blank=True, null=True, upload_to=apps.labs.models._report_file_path, verbose_name='DOCX')),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to=apps.labs.models._report_file_path, verbose_name='PDF')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='展示文件名')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='生成时间')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='labs.labsubmission', verbose_name='实验作答')),
            ],
            options={
                'verbose_name': '实验报告',
                'verbose_name_plural': '实验报告',
            },
        ),
        migrations.CreateModel(
            name='LabAttemptToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='票据')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='签发时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('consumed', models.BooleanField(default=False, verbose_name='已消费')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tokens', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_token', to='labs.labsubmission', verbose_name='实验作答')),
            ],
            options={
                'verbose_name': '实验桥接种子票据',
                'verbose_name_plural': '实验桥接种子票据',
            },
        ),
        migrations.CreateModel(
            name='LabAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student_answer', models.JSONField(blank=True, default=dict, verbose_name='学生答案')),
                ('is_correct', models.BooleanField(null=True, verbose_name='是否正确')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='最终得分')),
                ('auto_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='自动评分')),
                ('auto_comment', models.TextField(blank=True, verbose_name='自动评语')),
                ('similarity', models.FloatField(blank=True, null=True, verbose_name='相似度')),
                ('pending_review', models.BooleanField(default=False, verbose_name='待教师复核')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='批改时间')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_answer_gradings', to=settings.AUTH_USER_MODEL, verbose_name='批改人')),
                ('lab_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='labs.labquestion', verbose_name='实验题目')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='labs.labsubmission', verbose_name='实验作答')),
            ],
            options={
                'verbose_name': '实验作答明细',
                'verbose_name_plural': '实验作答明细',
                'ordering': ['lab_question__order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='labquestion',
            constraint=models.UniqueConstraint(fields=('lab', 'question'), name='unique_lab_question'),
        ),
        migrations.AddConstraint(
            model_name='labquestion',
            constraint=models.UniqueConstraint(fields=('lab', 'order'), name='unique_lab_question_order'),
        ),
        migrations.AddConstraint(
            model_name='labschedule',
            constraint=models.UniqueConstraint(fields=('lab', 'classroom'), name='unique_lab_classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='labsubmission',
            unique_together={('lab', 'student')},
        ),
        migrations.AddConstraint(
            model_name='labanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'lab_question'), name='unique_lab_submission_question'),
        ),
    ]
