# Generated by Django 5.1.4 on 2026-09-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_lab_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='allow_resubmit',
            field=models.BooleanField(default=True, verbose_name='允许学生重复提交'),
        ),
    ]
